ENV["RUBY_ENV"] = "test"
require "minitest/autorun"
require "webmock/minitest"
require_relative "../lib/programmer_helper_bot/chat_state"
require_relative "../lib/programmer_helper_bot/file_state_repository"
require_relative "../lib/programmer_helper_bot/chat_state_service"
require_relative "../lib/programmer_helper_bot/file_analyzer"
require_relative "../lib/programmer_helper_bot/link_shortener"
require_relative "../lib/programmer_helper_bot/python_sandbox"
require_relative "../lib/programmer_helper_bot/youtube_audio_downloader"
require_relative "../lib/programmer_helper_bot/message_router"
