AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - 'test/**/*'          
    - 'spec/**/*'           
    - 'features/**/*' 
    - 'bot.rb'      

# Остальные настройки
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Minitest правила для тестов не проверяем
require:
  - rubocop-minitest

Minitest/MultipleAssertions:
  Enabled: false